# Generated by Django 4.2 on 2026-01-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_candidate_company_usermaster_delete_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='role',
            field=models.CharField(max_length=50),
        ),
    ]
